/** @type {import('pm2').StartOptions} */
module.exports = {
  apps: [
    {
      name: "andersan-api",
      cwd: "/AIR/andersan-api",
      script: ".venv/bin/uvicorn",
      args: "andersan-api:app --host 0.0.0.0 --port 8087 --log-level info",
      interpreter: "none",
      env: {
        ANDERSAN_LOG_LEVEL: "INFO",
        CUDA_VISIBLE_DEVICES: "-1",
        // APW_BASE_URL: "http://andersan.net:8090",
        // APW_API_BEARER_TOKEN: "...",  // 未設定時は api_keys.toml の apw を使用
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      kill_timeout: 30000,
      merge_logs: true,
      time: true,
      out_file: "logs/pm2-andersan-api-out.log",
      error_file: "logs/pm2-andersan-api-error.log",
    },
    {
      name: "andersan-portforwarder",
      cwd: "/AIR/andersan-api",
      script: ".venv/bin/python",
      args: "portforwarder.py",
      interpreter: "none",
      env: {
        PORTFORWARDER_LOG_LEVEL: "INFO",
        PORTFORWARDER_LOCAL_PORT: "8087",
        PORTFORWARDER_REMOTE_PORT: "8087",
        PORTFORWARDER_SSH_HOST: "andersan.net",
        PORTFORWARDER_SSH_PORT: "22",
        PORTFORWARDER_SSH_USER: "ubuntu",
        PORTFORWARDER_WAIT_LOCAL_SEC: "120",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      kill_timeout: 15000,
      merge_logs: true,
      time: true,
      out_file: "logs/pm2-portforwarder-out.log",
      error_file: "logs/pm2-portforwarder-error.log",
    },
  ],
};
